# Generated by Django 4.2.29 on 2026-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('read_time', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('publish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['publish_date'], name='blog_articl_publish_19b608_idx')],
            },
        ),
    ]
