# Generated by Django 4.2.29 on 2026-05-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
